# Generated by Django 5.0.6 on 2024-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_login_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
