# Generated by Django 5.0.6 on 2024-06-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_login_id',
        ),
    ]
